### ISSUE TITLE
Build error related to urdfdom

### ISSUE THREAD

**Issue by alexdewar** [ros-noetic-arch/ros-noetic-diff-drive-controller#2] opened 2021-10-16 09:56 UTC
I'm getting the following error when trying to build this package:
```
==> Making package: ros-noetic-diff-drive-controller 0.19.0-2 (Sat 16 Oct 2021 10:55:49 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading ros-noetic-diff-drive-controller-0.19.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   136  100   136    0     0    406      0 --:--:-- --:--:-- --:--:--   407

100 14203    0 14203    0     0  21365      0 --:--:-- --:--:-- --:--:-- 21365
100  497k    0  497k    0     0   618k      0 --:--:-- --:--:-- --:--:-- 3481k
==> Validating source files with sha256sums...
    ros-noetic-diff-drive-controller-0.19.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting ros-noetic-diff-drive-controller-0.19.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- Using CATKIN_DEVEL_PREFIX: /tmp/makepkg/ros-noetic-diff-drive-controller/src/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Using empy: /usr/lib/python3.9/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/makepkg/ros-noetic-diff-drive-controller/src/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Using Python nosetests: /usr/bin/nosetests-3.9
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at /opt/ros/noetic/share/urdf/cmake/urdfConfig.cmake:173 (message):
  Project 'diff_drive_controller' tried to find library
  '$<$<NOT:$<CONFIG:Debug>>:/usr/lib/liburdfdom_sensor.so>'.  The library is
  neither a target nor built/installed properly.  Did you compile project
  'urdf'? Did you find_package() it before the subdirectory containing its
  code is included?
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/makepkg/ros-noetic-diff-drive-controller/src/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/makepkg/ros-noetic-diff-drive-controller/src/build/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...
```

Any ideas?

**Comment by acxz** [comment] 2022-01-31 19:46
I'll go ahead and close this issue as the root cause is in the above linked issue.

**Closed as completed by acxz** 2022-01-31 19:46 UTC
